# Generated by Django 4.2.4 on 2023-08-04 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('marrital_status', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('dob', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('height', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Qualification', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('work', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('experience', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('hobbies', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('income', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('medical_condition', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('about_me', models.TextField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
