# Generated by Django 4.2.4 on 2023-08-04 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_alter_profile_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='family_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('father_education', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('father_occupation', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mother_education', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mother_occupation', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sister', models.TextField(blank=True, null=True)),
                ('brother', models.TextField(blank=True, null=True)),
                ('native_place', models.TextField(blank=True, null=True)),
                ('relatives', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
