# Generated by Django 4.2.4 on 2023-08-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_family_details_gender_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
