# Generated by Django 4.2.4 on 2023-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_profile_is_featured_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
