# Generated by Django 4.2.4 on 2023-08-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='dp',
            field=models.ImageField(height_field=286, upload_to='media'),
        ),
    ]
