# Generated by Django 4.2.4 on 2023-08-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_media_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='dp',
            field=models.ImageField(upload_to='media'),
        ),
    ]
